export const SET_CALCULATION_METHOD = 'SET_CALCULATION_METHOD'

export const SET_MATRIX_SIZE_X = 'SET_MATRIX_SIZE_X'
export const SET_MATRIX_SIZE_Y = 'SET_MATRIX_SIZE_Y'

export const SET_MATRIX_ELEMENT = 'SET_MATRIX_ELEMENT'
export const SET_MATRIX_ELEMENT_SEQ_COMP = 'SET_MATRIX_ELEMENT_SEQ_COMP'
