export const SET_CALCULATION_METHOD = 'SET_CALCULATION_METHOD'
export const SET_CALCULATION_METHOD_PAIR_COMP =
    'SET_CALCULATION_METHOD_PAIR_COMP'
export const SET_CALCULATION_METHOD_SEQ_COMP = 'SET_CALCULATION_METHOD_SEQ_COMP'

export const SET_MATRIX_SIZE_X_INCREASE = 'SET_MATRIX_SIZE_X_INCREASE'
export const SET_MATRIX_SIZE_X_DECREASE = 'SET_MATRIX_SIZE_X_DECREASE'

export const SET_MATRIX_SIZE_Y_INCREASE = 'SET_MATRIX_SIZE_Y_INCREASE'
export const SET_MATRIX_SIZE_Y_DECREASE = 'SET_MATRIX_SIZE_Y_DECREASE'

export const SET_MATRIX_SIZE_Y_SEQ_COMP_INCREASE =
    'SET_MATRIX_SIZE_Y_SEQ_COMP_INCREASE'
export const SET_MATRIX_SIZE_Y_SEQ_COMP_DECREASE =
    'SET_MATRIX_SIZE_Y_SEQ_COMP_DECREASE'

export const SET_MATRIX_ELEMENT = 'SET_MATRIX_ELEMENT'

export const SET_MATRIX_ELEMENT_SEQ_COMP_INDEX =
    'SET_MATRIX_ELEMENT_SEQ_COMP_INDEX'
export const SET_MATRIX_ELEMENT_SEQ_COMP_WEIGHT =
    'SET_MATRIX_ELEMENT_SEQ_COMP_WEIGHT'
